# usage: conda env create --name envname --file=environment.yml
dependencies:
  - python=3.10
  - pip
  - pip:
    - --extra-index-url https://test.pypi.org/simple
    - git+https://github.com/BuildingGym/EnergyPlus-OOEP
    - git+https://github.com/SGHVAIC/EnergyPlus-Datasets
    - gymnasium
    - ray[rllib] 
    - torch
    - tqdm 